### PR TITLE
Get docker to run

### PR DESCRIPTION
**Pull request by neomatrix369**
- Added docker build and run shell scripts
- added docker and git ignore files
- fixed one of the docker image and container
- fixed notebook: pypy_comparison.ipynb
- partially fixed building of docker image in Analysis folder

@alexiglaser please try to run these scripts from this PR and see if it works for you. You notebook `pypy_comparison.ipynb` is looking for CSV files while algo_x.py was missing from the Algorithms folder

So far I haven't gotten any further because of the missing csv files.

### CODE REVIEW

**Comment by neomatrix369** [comment]
You want to add a check for timeout in this block https://github.com/alexiglaser/Constituency/blob/master/AlgorithmX/AlgorithmX.py#L133?

**Comment by alexiglaser** [comment]
The timeout should go in [here](https://github.com/alexiglaser/Constituency/blob/master/AlgorithmX/solutions.ipynb), in the ```return_solutions``` function

**Comment by neomatrix369** [comment]
> The timeout should go in [here](https://github.com/alexiglaser/Constituency/blob/master/AlgorithmX/solutions.ipynb), in the `return_solutions` function

Thanks I was looking in the wrong place I didn't get that far and scan through the notebooks properly.

**Comment by neomatrix369** [comment]
I get the below error when trying to build the docker container in the Analysis folder:

```
folder Analysis                   git branch:(get-docker-to-run) 
$ ./build-docker-image.sh
```

```
Building the pypi-Jupyter notebook docker image 'algox-analysis'...
Sending build context to Docker daemon  5.632kB
Step 1/7 : FROM jupyter/datascience-notebook:lab-2.1.1
 ---> 28aa5f90c90e
Step 2/7 : ENV CLOUD_SDK_VERSION 240.0.0
 ---> Using cache
 ---> a9c2e944855e
Step 3/7 : USER root
 ---> Using cache
 ---> bd0cddb5be55
Step 4/7 : RUN apt-get update     && apt-get -qqy install lsb-release gnupg2 build-essential
 ---> Running in f85a0c86ff4f
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Err:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
  At least one invalid signature was encountered.
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  At least one invalid signature was encountered.
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  At least one invalid signature was encountered.
Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://security.ubuntu.com/ubuntu bionic-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.ubuntu.com/ubuntu bionic-security InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu bionic InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu bionic-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-updates InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu bionic-backports InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-backports InRelease' is not signed.
The command '/bin/sh -c apt-get update     && apt-get -qqy install lsb-release gnupg2 build-essential' returned a non-zero code: 100
```

I'll look into it after you have given me an overall feedback of this PR. Don't run these scripts yet as they will give you the above error:
```
├── Analysis
│   ├── build-docker-image.sh
│   └── run-docker-container.sh
```

It would be great if we could use another base docker image to build this image, I mean wrt 
```
FROM jupyter/datascience-notebook:lab-2.1.1
```
maybe another version or another image tag totally. let me know if you have any tips - I will be digging into it when I look at it over the weekend.

**Pull request merged**
